spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mbtirannosaurus
    username: ssafy
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true

server:
  port: 8080
